### ISSUE TITLE
对比的baseline

### ISSUE THREAD

**Issue by zhaijianyang** [Abigale001/TMER#7]
大佬你好，为什么对比的方法都是很早的呀

**Comment by Abigale001** [comment]
学弟你好，因为这篇工作开始做的时候是2020年初，所以找了近2年的 github代码可以跑通的相关工作，以及经典的工作，进行比较。谢谢

**Comment by 0LEL0** [comment]
大佬你好，想问下这边有针对论文里baseline的数据处理代码吗
